MVCDemo/Controllers/ValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;
namespace MVCDemo.Controllers
{
    public class ValidationController : Controller
    {
        [HttpGet]
        // GET: Validation
        public ActionResult Index()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Student student)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else if (student.Name.Length < 3)
            {
                ModelState.AddModelError("Name", "姓名長度必須超過3碼");
                return View();
            }

            return RedirectToAction(nameof(Success));
        }

        public ActionResult Success()
        {
            return View();
        }
    }
}

MVCDemo/Views/Validation/Index.cshtml
@model MVCDemo.Models.Student

@{
    ViewBag.Title = "Index";
}

<h2>Validation Index</h2>
@using (Html.BeginForm("Index", "Validation", FormMethod.Post))
{ 
    @Html.AntiForgeryToken()

    @Html.LabelFor(m => m.Name)
    @Html.TextBoxFor(m => m.Name, )
    @Html.ValidationMessageFor(m => m.Name)
    <br />
    @Html.LabelFor(m => m.Age)
    @Html.TextBoxFor(m => m.Age)
    @Html.ValidationMessageFor(m => m.Age)

    <br />
    <button>送出</button>
}
@*<form action="@Url.Action("Index")" method="post">
    <input type="text" value="@Model.Name"/>
    <input type="text" value="@Model.Age" />
</form>*@

MVCDemo/Views/Validation/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>
@Html.ActionLink("回到Index", nameof(MVCDemo.Controllers.ValidationController.Index))