MVCDemo/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;
namespace MVCDemo.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexPartial()
        {
            Student s = (Student)Session["model"] ?? new Student { Name = "Yuzhen" };
            return PartialView("_IndexPartial", s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InsertPartial()
        {
            return PartialView("_InsertPartial");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(string name)
        {
            Student s = new Student { Name = name };
            Session["model"] = s;
            var data = new
            {
                IsSuccess = true
            };
            return Json(data);
        }
    }
}

MVCDemo/Views/Ajax/Index.cshtml
@model MVCDemo.Models.Student
@{
    ViewBag.Title = "Index";
}

<style>
    .border {
        border: 1px solid black;
        padding: 10px;
        border-radius: 10px;
        margin: 10px;
    }
</style>

<h2>Student</h2>
<div class="index-panel">
    @Html.Action("IndexPartial")
</div>
<div class="insert-panel"></div>
@*@Html.Action("InsertPartial")*@

@Html.AntiForgeryToken()

<button class="btn btn-default btn-show-new">New</button>


@section scripts{
    <script>
        var AntiKey = document.getElementsByName("__RequestVerificationToken")[0].value;
        $(function () {
            $('.btn-show-new').click(function () {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("InsertPartial")',
                    data: {
                        __RequestVerificationToken: AntiKey,
                    },
                    success: function (data) {
                        $('.insert-panel').html(data)
                        $('.btn-insert').click(function () {
                            $.ajax({
                                method: 'POST',
                                url: '@Url.Action("Insert")',
                                data: $('#insert-form').serialize(),
                                success: function (data) {
                                    if (data.IsSuccess === true)
                                    {
                                        $('.insert-panel').empty()
                                        $.ajax({
                                            method: 'GET',
                                            url: '@Url.Action("IndexPartial")',
                                            success: function (data) {
                                                $('.index-panel').html(data)
                                            }
                                        })
                                    }
                                }

                            })
                        })
                    }
                })
            })
        })
    </script>
    }

MVCDemo/Views/Ajax/_IndexPartial.cshtml
@model MVCDemo.Models.Student

    <div class="border">
        @Html.LabelFor(m => m.Name)
        @Html.DisplayFor(m => m.Name)
    </div>

MVCDemo/Views/Ajax/_InsertPartial.cshtml
@model MVCDemo.Models.Student
<div class="border">
    @using (Html.BeginForm("Insert", "Ajax", FormMethod.Post, new { id="insert-form"}))
    {
        @Html.AntiForgeryToken()
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)

        <button class="btn btn-danger btn-insert" type="button">Submit</button>
    }
</div>