MVCDemo/Controllers/HomeWork2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;
using MVCDemo.Service;

namespace MVCDemo.Controllers
{
    public class HomeWork2Controller : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult _DisplayEmpList()
        {
            if (Session["EmpList"] == null)
            {
                return PartialView(new List<EmployeeModel>());
            }
            else
            {
                return PartialView(Session["EmpList"] as List<EmployeeModel>);
            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeModel employee)
        {
            List<EmployeeModel> EmpList = new List<EmployeeModel>();
            if (Session["EmpList"] != null)
            {
                EmpList = Session["EmpList"] as List<EmployeeModel>;
            }
            if (employee.EmpID == null || GlobalMethods.CheckID(employee.EmpID) != "")
            {
                ModelState.AddModelError("EmpID", "身分證格式錯誤");
            }
            if (EmpList.Where(x => x.EmpID == employee.EmpID).Count() > 0)
            {
                ModelState.AddModelError("EmpID", "此身份證字號已重複");
            }

            if (employee.Birthday == null || employee.Birthday.Date > DateTime.Today)
            {
                ModelState.AddModelError("Birthday", "生日不可大於今天");
            }
            List<string> SexCheck = new List<string>();
            SexCheck.Add("1");
            SexCheck.Add("8");
            if (employee.Sex == "男" && !SexCheck.Contains(employee.EmpID.Substring(1, 1)))
            {
                ModelState.AddModelError("Sex", "性別選擇錯誤");
            }
            SexCheck.Clear();
            SexCheck.Add("2");
            SexCheck.Add("9");
            if (employee.Sex == "女" && !SexCheck.Contains(employee.EmpID.Substring(1, 1)))
            {
                ModelState.AddModelError("Sex", "性別選擇錯誤");
            }
            if (!ModelState.IsValid)
            {
                return View(employee);
            }

            EmpList.Add(employee);
            Session["EmpList"] = EmpList;
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            Session["SelectID"] = null;
            if (id == null || Session["EmpList"] == null)
            {
                return RedirectToAction("Index");
            }

            List<EmployeeModel> EmpList = Session["EmpList"] as List<EmployeeModel>;
            if (EmpList.Where(x => x.EmpID == id).Count() == 0)
            {
                return RedirectToAction("Index");
            }
            Session["SelectID"] = EmpList.Where(x => x.EmpID == id).Select(x => x.EmpID).FirstOrDefault();
            return View(EmpList.Where(x => x.EmpID == id).FirstOrDefault());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeModel employee)
        {
            if (Session["SelectID"] == null || Session["EmpList"] == null)
            {
                ModelState.AddModelError("EmpID", "非法的修改，請由列表進入");
                return View(employee);
            }

            List<EmployeeModel> EmpList = Session["EmpList"] as List<EmployeeModel>;
            string SelectID = Session["SelectID"] as string;
            if (SelectID != employee.EmpID)
            {
                ModelState.AddModelError("EmpID", "非法的修改，請由列表進入");
                return View(employee);
            }

            if (employee.Birthday == null || employee.Birthday.Date > DateTime.Today)
            {
                ModelState.AddModelError("Birthday", "生日不可大於今天");
            }
            List<string> SexCheck = new List<string>();
            SexCheck.Add("1");
            SexCheck.Add("8");
            if (employee.Sex == "男" && !SexCheck.Contains(employee.EmpID.Substring(1, 1)))
            {
                ModelState.AddModelError("Sex", "性別選擇錯誤");
            }
            SexCheck.Clear();
            SexCheck.Add("2");
            SexCheck.Add("9");
            if (employee.Sex == "女" && !SexCheck.Contains(employee.EmpID.Substring(1, 1)))
            {
                ModelState.AddModelError("Sex", "性別選擇錯誤");
            }
            if (!ModelState.IsValid)
            {
                return View(employee);
            }

            var Modify = EmpList.Where(x => x.EmpID == SelectID).FirstOrDefault();
            Modify.Birthday = employee.Birthday;
            Modify.EmpName = employee.EmpName;
            Modify.Sex = employee.Sex;

            Session["EmpList"] = EmpList;
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {
            if (id == null || Session["EmpList"] == null)
            {
                return RedirectToAction("Index");
            }
            List<EmployeeModel> EmpList = Session["EmpList"] as List<EmployeeModel>;
            if (EmpList.Where(x => x.EmpID == id).Count() == 0)
            {
                return RedirectToAction("Index");
            }
            EmpList.Remove(EmpList.Where(x => x.EmpID == id).FirstOrDefault());
            Session["EmpList"] = EmpList;
            return RedirectToAction("Index");
        }
    }
}

MVCDemo/Views/HomeWork2/Create.cshtml
@model MVCDemo.Models.EmployeeModel

@{
    ViewBag.Title = "Create";
    List<SelectListItem> selectListItems = new List<SelectListItem>();
    selectListItems.Add(new SelectListItem() { Text = "男", Value = "男" });
    selectListItems.Add(new SelectListItem() { Text = "女", Value = "女" });
}

<h2>Create</h2>

@using (Html.BeginForm("Create","HomeWork2", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EmployeeModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Sex, selectListItems, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCDemo/Views/HomeWork2/Edit.cshtml
@model MVCDemo.Models.EmployeeModel

@{
    ViewBag.Title = "Edit";
    List<SelectListItem> selectListItems = new List<SelectListItem>();
    selectListItems.Add(new SelectListItem() { Text = "男", Value = "男" });
    selectListItems.Add(new SelectListItem() { Text = "女", Value = "女" });
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EmployeeModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.EmpID)
                @Html.HiddenFor(model => model.EmpID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Sex, selectListItems, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCDemo/Views/HomeWork2/Index.cshtml
@{
    ViewBag.Title = "Index";
}


@Html.Action("_DisplayEmpList")

MVCDemo/Views/HomeWork2/_DisplayEmpList.cshtml
@model IEnumerable<MVCDemo.Models.EmployeeModel>
<h2>員工資料</h2>
<p>
    @Html.ActionLink("新增", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmpID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmpID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmpName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sex)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.ActionLink("修改", "Edit", new {  id=item.EmpID  }) |
            @Html.ActionLink("刪除", "Delete", new { id = item.EmpID })
        </td>
    </tr>
}

</table>